<?php

namespace App\Repositories\Eloquent\System\Remind;

use App\Repositories\Presenters\System\Remind\LogPresenter;
use Prettus\Repository\Eloquent\BaseRepository;
use Prettus\Repository\Criteria\RequestCriteria;
use App\Repositories\Interfaces\System\Remind\LogRepository;
use App\Models\System\Remind\Log;

/**
 * Class LogRepositoryEloquent.
 *
 * @package namespace App\Repositories\Eloquent\System\Remind;
 */
class LogRepositoryEloquent extends BaseRepository implements LogRepository
{
    /**
     * Specify Model class name
     *
     * @return string
     */
    public function model()
    {
        return Log::class;
    }

    public function presenter()
    {
        return app(LogPresenter::class); // TODO: Change the autogenerated stub
    }


    /**
     * Boot up the repository, pushing criteria
     */
    public function boot()
    {

    }

    public function adminList($title, $limit)
    {
        return $this->scopeQuery(function ($query) use ($title) {
            return $query->where('message', 'like', '%' . $title . '%');
        })->orderBy('id', 'desc')->paginate($limit);
    }

}
