<?php

namespace Modules\Mall\Repositories\Eloquent\Member\Base;

use Modules\Mall\Entities\Member\Base\Address;
use Modules\Mall\Repositories\Interfaces\Member\Base\AddressRepository;
use Modules\Mall\Repositories\Presenters\Member\Base\AddressPresenter;
use Prettus\Repository\Eloquent\BaseRepository;

/**
 * Class VideoRepositoryEloquent.
 *
 * @package namespace App\Repositories\Eloquent;
 */
class AddressRepositoryEloquent extends BaseRepository implements AddressRepository
{
    /**
     * Specify Model class name
     *
     * @return string
     */
    public function model()
    {
        return Address::class;
    }

    public function presenter()
    {
        return app(AddressPresenter::class); // TODO: Change the autogenerated stub
    }

    /**
     * Boot up the repository, pushing criteria
     */
    public function boot()
    {

    }

    public function resetDefault($id)
    {
        Address::where(['user_id' => $id])->update(['default' => 'no']);
    }

}
