<?php

namespace App\Repositories\Eloquent\System\Sms;

use App\Repositories\Presenters\System\Sms\RosterPresenter;
use Prettus\Repository\Eloquent\BaseRepository;
use Prettus\Repository\Criteria\RequestCriteria;
use App\Repositories\Interfaces\System\Sms\RosterRepository;
use App\Models\System\Sms\Roster;

/**
 * Class RosterRepositoryEloquent.
 *
 * @package namespace App\Repositories\Eloquent\System\Sms;
 */
class RosterRepositoryEloquent extends BaseRepository implements RosterRepository
{
    /**
     * Specify Model class name
     *
     * @return string
     */
    public function model()
    {
        return Roster::class;
    }

      public function presenter()
    {
        return app(RosterPresenter::class); // TODO: Change the autogenerated stub
    }

    /**
     * Boot up the repository, pushing criteria
     */
    public function boot()
    {

    }

}
