<?php

namespace App\Repositories\Eloquent\System\Sms;

use App\Repositories\Presenters\System\Sms\TemplatePresenter;
use Prettus\Repository\Eloquent\BaseRepository;
use Prettus\Repository\Criteria\RequestCriteria;
use App\Repositories\Interfaces\System\Sms\TemplateRepository;
use App\Models\System\Sms\Template;
use App\Validators\System\Sms\TemplateValidator;

/**
 * Class TemplateRepositoryEloquent.
 *
 * @package namespace App\Repositories\Eloquent\System\Sms;
 */
class TemplateRepositoryEloquent extends BaseRepository implements TemplateRepository
{
    /**
     * Specify Model class name
     *
     * @return string
     */
    public function model()
    {
        return Template::class;
    }

    public function presenter()
    {
        return app(TemplatePresenter::class); // TODO: Change the autogenerated stub
    }

    /**
     * Boot up the repository, pushing criteria
     */
    public function boot()
    {

    }

}
