<?php

namespace App\Repositories\Eloquent\System\Sms;

use App\Repositories\Presenters\System\Sms\TencentPresenter;
use Prettus\Repository\Eloquent\BaseRepository;
use Prettus\Repository\Criteria\RequestCriteria;
use App\Repositories\Interfaces\System\Sms\TencentRepository;
use App\Models\System\Sms\Tencent;
use App\Validators\System\Sms\TencentValidator;

/**
 * Class TencentRepositoryEloquent.
 *
 * @package namespace App\Repositories\Eloquent\System\Sms;
 */
class TencentRepositoryEloquent extends BaseRepository implements TencentRepository
{
    /**
     * Specify Model class name
     *
     * @return string
     */
    public function model()
    {
        return Tencent::class;
    }

    public function presenter()
    {
        return app(TencentPresenter::class); // TODO: Change the autogenerated stub
    }

    /**
     * Boot up the repository, pushing criteria
     */
    public function boot()
    {

    }

}
