<?php

namespace Modules\Mall\Repositories\Eloquent\Member\Withdrawal;

use Modules\Mall\Entities\Member\Withdrawal\Type;
use Modules\Mall\Repositories\Interfaces\Member\Withdrawal\TypeRepository;
use Modules\Mall\Repositories\Presenters\Member\Withdrawal\TypePresenter;
use Prettus\Repository\Eloquent\BaseRepository;

/**
 * Class VideoRepositoryEloquent.
 *
 * @package namespace App\Repositories\Eloquent;
 */
class TypeRepositoryEloquent extends BaseRepository implements TypeRepository
{
    /**
     * Specify Model class name
     *
     * @return string
     */
    public function model()
    {
        return Type::class;
    }

    public function presenter()
    {
        return app(TypePresenter::class); // TODO: Change the autogenerated stub
    }

    /**
     * Boot up the repository, pushing criteria
     */
    public function boot()
    {

    }

    public function option()
    {
        return Type::where(['status' => 'on'])->orderBy('sort', 'desc')->pluck('name', 'id');
    }

    public function adminList($title, $limit)
    {
        return $this->scopeQuery(function ($query) use ($title) {
            return $query->whereRaw("(concat(code,name) like '%" . $title . "%')");
        })->orderBy('sort', 'desc')->paginate($limit);
    }

}
