<?php

namespace Modules\Mall\Repositories\Eloquent\System;

use Modules\Mall\Entities\System\Notice;
use Modules\Mall\Repositories\Interfaces\System\NoticeRepository;
use Modules\Mall\Repositories\Presenters\System\NoticePresenter;
use Prettus\Repository\Eloquent\BaseRepository;

/**
 * Class VideoRepositoryEloquent.
 *
 * @package namespace App\Repositories\Eloquent;
 */
class NoticeRepositoryEloquent extends BaseRepository implements NoticeRepository
{
    /**
     * Specify Model class name
     *
     * @return string
     */
    public function model()
    {
        return Notice::class;
    }

    public function presenter()
    {
        return app(NoticePresenter::class); // TODO: Change the autogenerated stub
    }

    /**
     * Boot up the repository, pushing criteria
     */
    public function boot()
    {

    }

    public function adminList($title, $limit)
    {
        return $this->scopeQuery(function ($query) use ($title) {
            return $query->where('name', 'like', '%' . $title . '%');
        })->orderBy('status', 'desc')->orderBy('id', 'desc')->paginate($limit);
    }

}
