<?php

namespace Modules\Mall\Repositories\Eloquent\System;

use Modules\Mall\Entities\System\Online;
use Modules\Mall\Repositories\Interfaces\System\OnlineRepository;
use Modules\Mall\Repositories\Presenters\System\OnlinePresenter;
use Prettus\Repository\Eloquent\BaseRepository;

/**
 * Class VideoRepositoryEloquent.
 *
 * @package namespace App\Repositories\Eloquent;
 */
class OnlineRepositoryEloquent extends BaseRepository implements OnlineRepository
{
    /**
     * Specify Model class name
     *
     * @return string
     */
    public function model()
    {
        return Online::class;
    }

    public function presenter()
    {
        return app(OnlinePresenter::class); // TODO: Change the autogenerated stub
    }

    /**
     * Boot up the repository, pushing criteria
     */
    public function boot()
    {

    }



}
