<?php

namespace Modules\Mall\Repositories\Eloquent\System;

use Modules\Mall\Entities\System\Swipe;
use Modules\Mall\Repositories\Interfaces\System\SwipeRepository;
use Modules\Mall\Repositories\Presenters\System\SwipePresenter;
use Prettus\Repository\Eloquent\BaseRepository;

/**
 * Class VideoRepositoryEloquent.
 *
 * @package namespace App\Repositories\Eloquent;
 */
class SwipeRepositoryEloquent extends BaseRepository implements SwipeRepository
{
    /**
     * Specify Model class name
     *
     * @return string
     */
    public function model()
    {
        return Swipe::class;
    }

    public function presenter()
    {
        return app(SwipePresenter::class); // TODO: Change the autogenerated stub
    }

    /**
     * Boot up the repository, pushing criteria
     */
    public function boot()
    {

    }

    public function clientList($location)
    {
        return $this->scopeQuery(function ($query) use ($location) {
            return $query->where(['status' => 'on', 'location' => $location]);
        })->orderBy('sort', 'desc')->all();
    }

    public function adminList($title, $array, $limit)
    {
        return $this->scopeQuery(function ($query) use ($title, $array) {
            return $query->whereRaw("(concat(name) like '%" . $title . "%')")->where($array);
        })->orderBy('status', 'desc')->orderBy('sort', 'desc')->orderBy('id', 'desc')->paginate($limit);
    }

}
